/* CineBook Vanilla JS
   React-free recreation of the original app.
   Storage keys intentionally mirror the original project.
*/
const VERSION = "8.0-vanilla";
const KEY = {
  MOVIES: "cinebook_movies",
  CINEMAS: "cinebook_cinemas",
  SHOWS: "cinebook_shows",
  USERS: "cinebook_users",
  BOOKINGS: "cinebook_bookings",
  CURRENT: "cinebook_current_user",
  SEATS: "cinebook_booked_seats",
  VERSION: "cinebook_version",
};

const movies = [
  {
    id: "m1",
    title: "Avengers: Doomsday",
    description:
      "The Avengers face their greatest threat yet as Doctor Doom emerges from the shadows. With the multiverse hanging in the balance, Earth's mightiest heroes must assemble to prevent total annihilation in this epic 2026 blockbuster.",
    poster: "https://image.tmdb.org/t/p/w500/cWXtJhrlruF8CeYuaBGE8vdj3Q9.jpg",
    backdrop:
      "https://image.tmdb.org/t/p/original/cWXtJhrlruF8CeYuaBGE8vdj3Q9.jpg",
    genre: ["Action", "Sci-Fi", "Adventure"],
    language: "English",
    duration: 165,
    rating: null,
    certification: "UA",
    releaseDate: "2026-05-01",
    cast: ["Robert Downey Jr.", "Pedro Pascal", "Vanessa Kirby"],
    director: "Anthony Russo, Joe Russo",
    status: "coming_soon",
    formats: ["2D", "3D", "IMAX"],
  },
  {
    id: "m2",
    title: "Oppenheimer",
    description:
      "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop:
      "https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
    genre: ["Drama", "History"],
    language: "English",
    duration: 181,
    rating: 8.1,
    certification: "UA",
    releaseDate: "2023-07-19",
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."],
    director: "Christopher Nolan",
    status: "now_showing",
    formats: ["2D", "IMAX"],
  },
  {
    id: "m3",
    title: "Deadpool & Wolverine",
    description:
      "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
    poster: "https://image.tmdb.org/t/p/w500/v0Q2uYARIqui1sEBF0bCLJaliDI.jpg",
    backdrop:
      "https://image.tmdb.org/t/p/original/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
    genre: ["Action", "Comedy"],
    language: "English",
    duration: 128,
    rating: 7.7,
    certification: "A",
    releaseDate: "2024-07-24",
    cast: ["Ryan Reynolds", "Hugh Jackman", "Emma Corrin"],
    director: "Shawn Levy",
    status: "now_showing",
    formats: ["2D", "3D", "IMAX"],
  },
  {
    id: "m4",
    title: "Avatar: Fire and Ash",
    description:
      "The third installment in the Avatar franchise. Jake Sully and Neytiri face a new, aggressive Na'vi tribe known as the Ash People, pushing the boundaries of Pandora's vast world.",
    poster: "https://image.tmdb.org/t/p/w500/qnzQm0PCVnSyv1dqpVmRgMWHbLD.jpg",
    backdrop:
      "https://image.tmdb.org/t/p/original/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
    genre: ["Sci-Fi", "Action", "Adventure"],
    language: "English",
    duration: 195,
    rating: 8,
    certification: "UA",
    releaseDate: "2025-12-19",
    cast: ["Sam Worthington", "Zoe Saldaña", "Sigourney Weaver"],
    director: "James Cameron",
    status: "now_showing",
    formats: ["3D", "IMAX"],
  },
  {
    id: "m5",
    title: "Dune: Part Two",
    description:
      "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.",
    poster: "https://image.tmdb.org/t/p/w500/3HzGtM0JpfH2pWFGugJK22LRP6b.jpg",
    backdrop:
      "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    genre: ["Sci-Fi", "Adventure"],
    language: "English",
    duration: 167,
    rating: 8.2,
    certification: "UA",
    releaseDate: "2024-02-27",
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson"],
    director: "Denis Villeneuve",
    status: "now_showing",
    formats: ["2D", "IMAX"],
  },
  {
    id: "m6",
    title: "Transformers: Rise of the Beasts",
    description:
      "When a new threat capable of destroying the entire planet emerges, Optimus Prime and the Autobots must team up with a powerful faction known as the Maximals.",
    poster: "https://image.tmdb.org/t/p/w500/gPbM0MK8CP8A174rmUwGsADNYKD.jpg",
    backdrop:
      "https://image.tmdb.org/t/p/original/2vFuG6bWGyQUzYS9d69E5l85nIz.jpg",
    genre: ["Action", "Adventure", "Sci-Fi"],
    language: "English",
    duration: 127,
    rating: 7.3,
    certification: "UA",
    releaseDate: "2023-06-06",
    cast: ["Anthony Ramos", "Dominique Fishback"],
    director: "Steven Caple Jr.",
    status: "now_showing",
    formats: ["2D", "3D", "IMAX"],
  },
  {
    id: "m7",
    title: "Jawan",
    description:
      "An emotional journey of a prison warden, driven by a personal vendetta while keeping up to a promise made years ago, recruits inmates to commit outrageous crimes.",
    poster: "https://image.tmdb.org/t/p/w500/5Y36lCiNyyV71mjq6LavgiggbhT.jpg",
    backdrop:
      "https://image.tmdb.org/t/p/original/8pjWz2lt29KyVGoq1mEBrmVYdKw.jpg",
    genre: ["Action", "Thriller"],
    language: "Hindi",
    duration: 169,
    rating: 7.2,
    certification: "UA",
    releaseDate: "2023-09-07",
    cast: ["Shah Rukh Khan", "Nayanthara", "Vijay Sethupathi"],
    director: "Atlee",
    status: "now_showing",
    formats: ["2D", "IMAX"],
  },
  {
    id: "m8",
    title: "Spider-Man: Beyond the Spider-Verse",
    description:
      "The epic conclusion to the Spider-Verse trilogy. Miles Morales must face his destiny and save the multiverse while dealing with the repercussions of his previous adventures.",
    poster: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    backdrop:
      "https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    genre: ["Animation", "Action", "Adventure"],
    language: "English",
    duration: 145,
    rating: null,
    certification: "U",
    releaseDate: "2026-11-15",
    cast: ["Shameik Moore", "Hailee Steinfeld", "Oscar Isaac"],
    director: "Joaquim Dos Santos",
    status: "coming_soon",
    formats: ["2D", "3D"],
  },
  {
    id: "m9",
    title: "John Wick: Chapter 4",
    description:
      "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table.",
    poster: "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
    backdrop:
      "https://image.tmdb.org/t/p/original/7I6VUdPj6tQECNHdviJkUHD2u89.jpg",
    genre: ["Action", "Thriller"],
    language: "English",
    duration: 170,
    rating: 7.8,
    certification: "A",
    releaseDate: "2023-03-22",
    cast: ["Keanu Reeves", "Donnie Yen", "Bill Skarsgård"],
    director: "Chad Stahelski",
    status: "now_showing",
    formats: ["2D", "IMAX"],
  },
  {
    id: "m10",
    title: "The Batman Part II",
    description:
      "The highly anticipated 2026 sequel to The Batman. Bruce Wayne dives deeper into the criminal underworld of Gotham City as a new, terrifying villain emerges to challenge his crusade.",
    poster: "https://image.tmdb.org/t/p/w500/djCPA8NYhhsDT1DVTViOgH4INqY.jpg",
    backdrop:
      "https://image.tmdb.org/t/p/original/b0PlSFdTaMq4MquZkR53iK0LzF.jpg",
    genre: ["Crime", "Mystery", "Action"],
    language: "English",
    duration: 180,
    rating: null,
    certification: "UA",
    releaseDate: "2026-10-02",
    cast: ["Robert Pattinson", "Zoë Kravitz", "Colin Farrell"],
    director: "Matt Reeves",
    status: "coming_soon",
    formats: ["2D", "IMAX"],
  },
  {
    id: "m11",
    title: "Venom: The Last Dance",
    description:
      "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
    poster: "https://image.tmdb.org/t/p/w500/vGXptEdgZIhPg3cGlc7e8sNPC2e.jpg",
    backdrop: "https://image.tmdb.org/t/p/w500/vGXptEdgZIhPg3cGlc7e8sNPC2e.jpg",
    genre: ["Action", "Sci-Fi"],
    language: "English",
    duration: 110,
    rating: 7.5,
    certification: "UA",
    releaseDate: "2024-10-25",
    cast: ["Tom Hardy", "Chiwetel Ejiofor", "Juno Temple"],
    director: "Kelly Marcel",
    status: "now_showing",
    formats: ["2D", "IMAX", "3D"],
  },
  {
    id: "m12",
    title: "Moana 2",
    description:
      "Three years since her first voyage, Moana is on an expansive journey in search of people beyond the shores of Motunui.",
    poster: "https://image.tmdb.org/t/p/w500/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg",
    backdrop: "https://image.tmdb.org/t/p/w500/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg",
    genre: ["Animation", "Adventure"],
    language: "English",
    duration: 105,
    rating: 8,
    certification: "U",
    releaseDate: "2024-11-27",
    cast: ["Auliʻi Cravalho", "Dwayne Johnson", "Alan Tudyk"],
    director: "David Derrick Jr.",
    status: "now_showing",
    formats: ["2D", "3D"],
  },
  {
    id: "m13",
    title: "Gladiator II",
    description:
      "Years after witnessing the death of the revered hero Maximus, Lucius is forced to enter the Colosseum after his home is conquered by tyrannical Emperors.",
    poster: "https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    backdrop: "https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    genre: ["Action", "Drama", "History"],
    language: "English",
    duration: 150,
    rating: 8.2,
    certification: "A",
    releaseDate: "2024-11-15",
    cast: ["Paul Mescal", "Pedro Pascal", "Denzel Washington"],
    director: "Ridley Scott",
    status: "now_showing",
    formats: ["2D", "IMAX"],
  },
  {
    id: "m14",
    title: "La La Land",
    description:
      "Mia, an aspiring actress, serves lattes to movie stars in between auditions and Sebastian, a jazz musician, scrapes by playing cocktail party gigs in dingy bars.",
    poster: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    backdrop:
      "https://image.tmdb.org/t/p/original/qJeU7KM4nT2C1WpOrwPcSDGFUWE.jpg",
    genre: ["Comedy", "Drama", "Romance"],
    language: "English",
    duration: 128,
    rating: 8,
    certification: "UA",
    releaseDate: "2016-11-29",
    cast: ["Ryan Gosling", "Emma Stone", "John Legend"],
    director: "Damien Chazelle",
    status: "now_showing",
    formats: ["2D"],
  },
];

const cinemas = [
  {
    id: "c1",
    name: "CineMax Multiplex",
    location: "Mumbai",
    address: "Andheri West, Link Road, Mumbai 400053",
    facilities: [
      "Parking",
      "Food Court",
      "Dolby Atmos",
      "IMAX",
      "Wheelchair Access",
    ],
    screens: [
      {
        id: "sc1",
        name: "Screen 1 - IMAX",
        rows: 10,
        seatsPerRow: 12,
        seatTypes: {
          premium: ["A", "B"],
          standard: ["C", "D", "E", "F", "G", "H"],
          economy: ["I", "J"],
        },
      },
      {
        id: "sc2",
        name: "Screen 2",
        rows: 8,
        seatsPerRow: 10,
        seatTypes: {
          premium: ["A", "B"],
          standard: ["C", "D", "E", "F"],
          economy: ["G", "H"],
        },
      },
    ],
  },
  {
    id: "c2",
    name: "Galaxy Cinemas",
    location: "Delhi",
    address: "Connaught Place, New Delhi 110001",
    facilities: ["Parking", "Food Court", "Dolby Atmos", "Wheelchair Access"],
    screens: [
      {
        id: "sc4",
        name: "Screen 1",
        rows: 8,
        seatsPerRow: 12,
        seatTypes: {
          premium: ["A", "B"],
          standard: ["C", "D", "E", "F", "G", "H"],
          economy: ["I", "J"],
        },
      },
    ],
  },
  {
    id: "c3",
    name: "PVR Icon",
    location: "Bangalore",
    address: "Whitefield Main Road, Bengaluru 560066",
    facilities: [
      "Parking",
      "Food Court",
      "IMAX",
      "Recliners",
      "Wheelchair Access",
    ],
    screens: [
      {
        id: "sc5",
        name: "Screen 1 - IMAX",
        rows: 10,
        seatsPerRow: 12,
        seatTypes: {
          premium: ["A", "B", "C"],
          standard: ["D", "E", "F", "G", "H", "I"],
          economy: ["J", "K"],
        },
      },
    ],
  },
  {
    id: "c4",
    name: "Cinepolis",
    location: "Mumbai",
    address: "Thane West, Mumbai 400601",
    facilities: ["Parking", "Food Court", "4DX", "Dolby Atmos"],
    screens: [
      {
        id: "sc6",
        name: "Screen 1",
        rows: 8,
        seatsPerRow: 10,
        seatTypes: {
          premium: ["A", "B"],
          standard: ["C", "D", "E", "F"],
          economy: ["G", "H"],
        },
      },
    ],
  },
];

const users = [
  {
    _id: "u1",
    name: "Aarav Sharma",
    email: "aarav@example.com",
    password: "password123",
    role: "user",
    createdAt: "2026-01-10",
  },
  {
    _id: "u2",
    name: "Priya Singh",
    email: "priya@example.com",
    password: "password123",
    role: "user",
    createdAt: "2026-01-12",
  },
  {
    _id: "admin1",
    name: "Admin",
    email: "admin@cinebook.com",
    password: "admin123",
    role: "admin",
    createdAt: "2026-01-01",
  },
];

const offers = [
  [
    "First Booking Discount",
    "New to CineBook? Get 20% off on your first movie ticket. Create an account and use the code at checkout.",
    "FIRST20",
    "Oct 31, 2026",
    "New Users",
  ],
  [
    "Weekend Movie Mania",
    "Enjoy a flat ₹50 discount on Standard seats for any movie booked on Saturday or Sunday. No minimum order required.",
    "WEEKEND50",
    "Every Weekend",
    "All Users",
  ],
  [
    "Premium Seat Upgrade",
    "Experience Premium seating at Standard prices on all weekday shows before 4 PM. Subject to seat availability.",
    "UPGRADE",
    "Nov 15, 2026",
    "Limited Period",
  ],
  [
    "Student Pass",
    "15% off on all bookings with a valid student ID. Show your college ID at the cinema entrance for verification.",
    "STUDENT15",
    "Dec 31, 2026",
    "Students",
  ],
  [
    "IMAX for Less",
    "Book any IMAX show on Tuesdays and get ₹100 off per ticket.",
    "IMAXTUE",
    "Every Tuesday",
    "IMAX",
  ],
  [
    "Refer & Earn",
    "Invite a friend to CineBook. When they complete their first booking, both of you get ₹75 off on your next ticket.",
    "REFERWIN",
    "Nov 30, 2026",
    "Referral",
  ],
];
